<?php

return [
    'roles' => [
        'member' => [
            'name' => 'Member',
            'description' => 'Access curated opportunities, resources, and community support across Athena.',
            'icon' => 'fas fa-user-astronaut',
            'color' => '#E91E8C',
            'dashboard_route' => 'member.dashboard',
            'features' => [
                'Browse women-first job opportunities',
                'Set personalized alerts across hubs',
                'Connect with mentors and community',
            ],
        ],
        'company' => [
            'name' => 'Company',
            'description' => 'Showcase your workplace, roles, and equity commitments.',
            'icon' => 'fas fa-building',
            'color' => '#8B5CF6',
            'dashboard_route' => 'company.dashboard',
            'features' => [
                'Post open roles and programs',
                'Showcase culture commitments',
                'Access diverse talent pipelines',
            ],
        ],
        'mentor' => [
            'name' => 'Mentor',
            'description' => 'Offer hands-on guidance, coaching, and sponsorship.',
            'icon' => 'fas fa-hands-holding-heart',
            'color' => '#10B981',
            'dashboard_route' => 'member.dashboard',
            'features' => [
                'Create mentorship pathways',
                'Track mentee goals and wins',
                'Access mentor-only programming',
            ],
        ],
        'public_sector' => [
            'name' => 'Public Sector',
            'description' => 'Unlock civic labs, procurement missions, and agency dashboards.',
            'icon' => 'fas fa-landmark',
            'color' => '#3B82F6',
            'dashboard_route' => 'public-sector.dashboard',
            'features' => [
                'Share procurement opportunities',
                'Coordinate civic innovation missions',
                'Connect with high-intent partners',
            ],
        ],
        'tafe_university' => [
            'name' => 'TAFE / University',
            'description' => 'Partner on learning pathways, cohorts, and wraparound support.',
            'icon' => 'fas fa-graduation-cap',
            'color' => '#F59E0B',
            'dashboard_route' => 'education.tafe.dashboard',
            'features' => [
                'Showcase courses and programs',
                'Manage cohorts and journeys',
                'Offer scholarships and wraparound care',
            ],
        ],
        'business_network' => [
            'name' => 'Business Network',
            'description' => 'Connect founders, suppliers, and ecosystem partners.',
            'icon' => 'fas fa-network-wired',
            'color' => '#EC4899',
            'dashboard_route' => 'business.dashboard',
            'features' => [
                'Promote women-owned ventures',
                'Share supplier opportunities',
                'Collaborate on distribution deals',
            ],
        ],
        'real_estate_agent' => [
            'name' => 'Real Estate Agent',
            'description' => 'List women-first housing and relocation programs.',
            'icon' => 'fas fa-house-chimney',
            'color' => '#06B6D4',
            'dashboard_route' => 'women.real-estate.dashboard',
            'features' => [
                'Publish listings and relocation bundles',
                'Coordinate with verified partners',
                'Offer relocation support journeys',
            ],
        ],
        'real_estate_seeker' => [
            'name' => 'Property Seeker',
            'description' => 'Find safe, women-first housing pathways.',
            'icon' => 'fas fa-person-shelter',
            'color' => '#14B8A6',
            'dashboard_route' => 'women.real-estate.dashboard',
            'features' => [
                'Discover verified listings',
                'Match with trusted agents',
                'Access affordability tools',
            ],
        ],
        'trades_professional' => [
            'name' => 'Trades Professional',
            'description' => 'Champion trades apprenticeships and pathways.',
            'icon' => 'fas fa-hard-hat',
            'color' => '#F97316',
            'dashboard_route' => 'member.dashboard',
            'features' => [
                'Post apprenticeships and traineeships',
                'Mentor incoming trades talent',
                'Share pathways into trades',
            ],
        ],
        'health_wellness_provider' => [
            'name' => 'Health & Wellness Provider',
            'description' => 'Offer fitness, mindfulness, and wellbeing services.',
            'icon' => 'fas fa-heart-pulse',
            'color' => '#84CC16',
            'dashboard_route' => 'business.dashboard',
            'features' => [
                'List wellness programs',
                'Host restorative events',
                'Share holistic wellbeing resources',
            ],
        ],
        'beauty_fashion_provider' => [
            'name' => 'Beauty & Fashion Provider',
            'description' => 'Showcase beauty, fashion, and lifestyle experiences.',
            'icon' => 'fas fa-sparkles',
            'color' => '#D946EF',
            'dashboard_route' => 'business.dashboard',
            'features' => [
                'Highlight women-owned brands',
                'Launch exclusive drops',
                'Engage community members',
            ],
        ],
        'financial_advisor' => [
            'name' => 'Financial Advisor',
            'description' => 'Deliver holistic financial education and advisory programs.',
            'icon' => 'fas fa-chart-line',
            'color' => '#EAB308',
            'dashboard_route' => 'business.dashboard',
            'features' => [
                'Offer literacy workshops',
                'Build personalized plans',
                'Share money confidence toolkits',
            ],
        ],
        'sole_trader' => [
            'name' => 'Sole Trader',
            'description' => 'Access business tools, financial software, and wraparound resources.',
            'icon' => 'fas fa-briefcase',
            'color' => '#6366F1',
            'dashboard_route' => 'business.dashboard',
            'features' => [
                'Use lightweight finance tooling',
                'Track income and expenses',
                'Find grants and partners',
            ],
        ],
    ],

    'interests' => [
        'jobs' => 'Career opportunities',
        'housing' => 'Housing & real estate',
        'business' => 'Business & entrepreneurship',
        'health' => 'Health & wellness',
        'beauty' => 'Beauty & fashion',
        'finance' => 'Financial literacy',
        'education' => 'Education & training',
        'trades' => 'Trades & apprenticeships',
        'networking' => 'Community & networking',
        'mentorship' => 'Mentorship programs',
    ],

    'pronouns' => [
        'She / Her',
        'He / Him',
        'They / Them',
        'She / They',
        'He / They',
        'Prefer not to say',
    ],

    'locations' => [
        'NSW' => 'New South Wales',
        'VIC' => 'Victoria',
        'QLD' => 'Queensland',
        'WA' => 'Western Australia',
        'SA' => 'South Australia',
        'TAS' => 'Tasmania',
        'ACT' => 'Australian Capital Territory',
        'NT' => 'Northern Territory',
        'REMOTE' => 'Remote / Online',
    ],

    'home_sections' => [
        [
            'slug' => 'public-sector',
            'label' => 'Public Sector',
            'icon' => 'shield-checkmark-outline',
            'eyebrow' => 'Civic labs & procurement',
            'description' => 'Co-design inclusive missions with agencies, procurement squads, and AI compliance aides.',
            'stat_value' => '18',
            'stat_label' => 'agency labs live',
            'insight' => 'Problem Map 1.3 highlighted women missing from civic pathways; this hub pairs procurement briefs with wraparound mentors.',
            'supporting_points' => [
                'Publish equitable procurement missions and cadetships',
                'Civic AI scripts summarise legislation for women-first vendors',
                'Mentor bench featuring verified SES and APS women leaders',
            ],
            'cta' => [
                'label' => 'Open public sector lab',
                'route' => 'public-sector.dashboard',
            ],
            'theme' => [
                'accent' => '#3B82F6',
                'surface' => '#E0F2FE',
            ],
        ],
        [
            'slug' => 'member',
            'label' => 'Member / Candidate',
            'icon' => 'people-outline',
            'eyebrow' => 'Career rituals studio',
            'description' => 'AI-guided profiles, wishlist tracking, and verified mentors rebuild confidence for every career restart.',
            'stat_value' => '47',
            'stat_label' => 'live rituals this week',
            'insight' => 'Critical Problems dossier shows gender pay gap at 11.5% and confidence erosion; we front-load rituals and micro-wins.',
            'supporting_points' => [
                'Dream job wishlist and instant alerts when roles open',
                'Interview labs with human and AI scoring',
                'Safety prompts, pronouns, and rest-first reminders every login',
            ],
            'cta' => [
                'label' => 'Browse member stories',
                'route' => 'members.index',
            ],
            'theme' => [
                'accent' => '#EC4899',
                'surface' => '#FDF2F8',
            ],
        ],
        [
            'slug' => 'company',
            'label' => 'Company',
            'icon' => 'briefcase-outline',
            'eyebrow' => 'Equity employer studio',
            'description' => 'Showcase pay transparency, leadership ratios, and care policies with living impact tiles.',
            'stat_value' => '62',
            'stat_label' => 'companies verified',
            'insight' => 'Women retire with 25% less super; we surface employer data so women can filter by policies before applying.',
            'supporting_points' => [
                'Upload leadership and pay equity dashboards',
                'Plug in salary bands plus negotiation ranges',
                'Sponsor micro-grants or data plans straight from dashboard',
            ],
            'cta' => [
                'label' => 'Feature your workplace',
                'route' => 'companies.index',
            ],
            'theme' => [
                'accent' => '#6366F1',
                'surface' => '#EEF2FF',
            ],
        ],
        [
            'slug' => 'health-fitness',
            'label' => 'Health & Fitness',
            'icon' => 'barbell-outline',
            'eyebrow' => 'Wellness & recovery loops',
            'description' => 'Clinicians, coaches, and AI concierge plans keep care, movement, and rest-first rituals within reach.',
            'stat_value' => '320',
            'stat_label' => 'care pathways live',
            'insight' => 'Problem Map shows burnout, isolation, and health debt compounding financial stress; health loops translate referrals into daily rituals.',
            'supporting_points' => [
                'Sync telehealth, physiotherapy, and women-first GP notes in one plan',
                'AI-generated recovery nudges and safety check-ins',
                'Micro-grants for gym memberships, allied health, and cultural healers',
            ],
            'cta' => [
                'label' => 'Visit wellness commons',
                'route' => 'wellness.hub',
            ],
            'theme' => [
                'accent' => '#F472B6',
                'surface' => '#FEF3F7',
            ],
        ],
        [
            'slug' => 'tafe-university',
            'label' => 'TAFE / University',
            'icon' => 'school-outline',
            'eyebrow' => 'Learning pathways',
            'description' => 'Publish micro-credentials, bridging programs, and wraparound care calendars for women-first cohorts.',
            'stat_value' => '74',
            'stat_label' => 'programs curated',
            'insight' => 'Problem Map 1.3 notes the leaky STEM pipeline; we expose entry data, scholarships, and childcare add-ons up front.',
            'supporting_points' => [
                'Editable intake timelines and application scripts',
                'Placements feed into Dream Pathways wishlists',
                'Compliance-ready evidence for partner funding',
            ],
            'cta' => [
                'label' => 'Show your pathways',
                'route' => 'education.discovery',
            ],
            'theme' => [
                'accent' => '#F59E0B',
                'surface' => '#FFF7ED',
            ],
        ],
        [
            'slug' => 'business-network',
            'label' => 'Business Network',
            'icon' => 'git-network-outline',
            'eyebrow' => 'Supplier and founder mesh',
            'description' => 'Connect women-owned suppliers with anchor buyers, accelerators, and micro-finance allies.',
            'stat_value' => '128',
            'stat_label' => 'intros brokered quarterly',
            'insight' => 'Business hub research flagged funding glass walls; this network tracks equity, legal templates, and grant readiness.',
            'supporting_points' => [
                'Share deal room updates with ethical advertising inventory',
                'AI grant desk summarises eligibility and deadlines',
                'Legal and tax playbooks reduce admin panic',
            ],
            'cta' => [
                'label' => 'Enter business network',
                'route' => 'business.network',
            ],
            'theme' => [
                'accent' => '#EC4899',
                'surface' => '#FFE4F3',
            ],
        ],
        [
            'slug' => 'real-estate',
            'label' => 'Real Estate',
            'icon' => 'home-outline',
            'eyebrow' => 'Housing safety lab',
            'description' => 'Pair verified landlords, women-first brokers, and safety checklists to reduce housing precarity.',
            'stat_value' => '312',
            'stat_label' => 'vetted listings today',
            'insight' => 'Problem Map 1.2 shows older single women leading homelessness stats; this lab enforces trauma-informed onboarding.',
            'supporting_points' => [
                'Live mortgage and rent calculators tuned to single incomes',
                'Safety badges covering DV risk and cultural needs',
                'Escalation into grants and legal advocates when red flags fire',
            ],
            'cta' => [
                'label' => 'Browse housing support',
                'route' => 'housing.index',
            ],
            'theme' => [
                'accent' => '#0EA5E9',
                'surface' => '#E0F2FE',
            ],
        ],
        [
            'slug' => 'trades',
            'label' => 'Trades & Apprenticeships',
            'icon' => 'construct-outline',
            'eyebrow' => 'Tools down stigma hub',
            'description' => 'Showcase apprenticeships, PPE grants, and allied mentors to combat the leaky trades pipeline.',
            'stat_value' => '56',
            'stat_label' => 'apprentice cohorts funded',
            'insight' => 'Problem Map flagged stereotypes and harassment; we bundle vetted crews, locker-room policies, and emergency support.',
            'supporting_points' => [
                'Pre-commitment briefs so women know exact site culture',
                'AI collects micro-feedback to flag hostile crews early',
                'Tool library and childcare vouchers funded by sponsors',
            ],
            'cta' => [
                'label' => 'See trades map',
                'route' => 'jobs.index',
            ],
            'theme' => [
                'accent' => '#F97316',
                'surface' => '#FFF7ED',
            ],
        ],
        [
            'slug' => 'financial-wellbeing',
            'label' => 'Financial Literacy & Wellbeing',
            'icon' => 'cash-outline',
            'eyebrow' => 'Money & care desk',
            'description' => 'Budget diagnostics, subscription audits, and trauma-aware coaches rebuild safety nets.',
            'stat_value' => '$1.2M',
            'stat_label' => 'relief unlocked',
            'insight' => 'Problem Map 1.1 shows 69% of households under stress; this desk automates calm explainers and micro relief.',
            'supporting_points' => [
                'Subscription leak detector tied to bank feeds',
                'Debt triage with snowball and avalanche simulators',
                'Push-button referrals to accredited financial counsellors',
            ],
            'cta' => [
                'label' => 'Open money inbox',
                'route' => 'financial.budget',
            ],
            'theme' => [
                'accent' => '#EAB308',
                'surface' => '#FEF9C3',
            ],
        ],
        [
            'slug' => 'mobility',
            'label' => 'New / Preloved Cars',
            'icon' => 'car-sport-outline',
            'eyebrow' => 'Mobility concierge',
            'description' => 'EV concierge, safety-audited used cars, and co-funded servicing keep women mobile.',
            'stat_value' => '3-step',
            'stat_label' => 'buying concierge',
            'insight' => 'Problem Map flagged transport costs as career blockers; concierge blends financing mentors with sponsor relief.',
            'supporting_points' => [
                'Compare EV, hybrid, and fuel-efficient models with care data',
                'Mentors decode financing, insurance, and salary packaging',
                'Relief fund offsets rego, servicing, and safety tech',
            ],
            'cta' => [
                'label' => 'Book mobility consult',
                'route' => 'contact.index',
            ],
            'theme' => [
                'accent' => '#7C3AED',
                'surface' => '#F3E8FF',
            ],
        ],
        [
            'slug' => 'ai-concierge',
            'label' => 'AI Concierge',
            'icon' => 'color-wand-outline',
            'eyebrow' => 'Athena AI copilots',
            'description' => 'Research-backed prompts unify resume scans, grant drafting, budgeting, and wellbeing nudges.',
            'stat_value' => '24 hr',
            'stat_label' => 'context memory',
            'insight' => 'Copilot guide plus Problem Map data feed guardrails so AI stays trauma-informed and bias-aware.',
            'supporting_points' => [
                'Career, housing, money, and wellbeing personas',
                'Rate limiting with fallbacks to human teams when needed',
                'Explains next-best action referencing research citations',
            ],
            'cta' => [
                'label' => 'Launch AI concierge',
                'route' => 'ai.concierge',
            ],
            'theme' => [
                'accent' => '#6366F1',
                'surface' => '#EEF2FF',
            ],
        ],
        [
            'slug' => 'social-feed',
            'label' => 'Social Feed & Mentorship',
            'icon' => 'chatbubbles-outline',
            'eyebrow' => 'Circles & broadcast',
            'description' => 'Moderated social feed, live rooms, and emergency broadcasts keep women connected and safe.',
            'stat_value' => '4.2K',
            'stat_label' => 'community stories',
            'insight' => 'Problem Map notes isolation and abuse risks; social ops keep channels moderated with AI and human stewards.',
            'supporting_points' => [
                'Topic-specific feeds covering housing, business, wellness',
                'On-call moderators and escalation to support workers',
                'Signal-boost for grants, housing alerts, and wins',
            ],
            'cta' => [
                'label' => 'Explore the feed',
                'route' => 'feed.index',
            ],
            'theme' => [
                'accent' => '#0EA5E9',
                'surface' => '#E0F2FE',
            ],
        ],
    ],
];
