'use client';

/**
 * The automotive admin queues: workshops and dealerships to verify (and
 * feature), listings held by the checks, purchases in dispute, finance
 * applications for the desk, and inspection requests nobody has taken.
 */

import { useState } from 'react';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { ShieldCheck } from 'lucide-react';
import { autoApi, autoError, aud0, km, type ApplicationCard, type DealershipCard, type InspectionCard, type ListingCard, type MechanicCard, type PurchaseCard, type ReferralCard, type ReferralFees, type ReferralTotals } from '@/lib/automotive-api';
import { AutoNav, Confirm, ErrorBox, Loading, PageTitle, StatusChip, fmtDay, useLoad } from '@/components/automotive/AutoUi';
import { Field, NumberInput, Panel, SelectInput, inputClass, num } from '@/components/strategy/StrategyUi';

type Overview = { counts: { verifiedMechanics: number; verifiedDealers: number; liveListings: number; openPurchases: number }; referrals: { totals: ReferralTotals; open: ReferralCard[]; fees: ReferralFees }; mechanics: Array<MechanicCard & { about: string; licenceNumber: string | null; createdAt: string }>; dealerships: Array<DealershipCard & { about: string | null; email: string | null; createdAt: string }>; listings: ListingCard[]; disputes: PurchaseCard[]; applications: ApplicationCard[]; inspections: InspectionCard[] };

const REFERRAL_KINDS = [{ value: 'INSURANCE', label: 'Insurance' }, { value: 'WARRANTY', label: 'Extended warranty' }, { value: 'PARTS', label: 'Parts' }, { value: 'FINANCE', label: 'Finance' }, { value: 'DEALER_SALE', label: 'Dealership sale' }, { value: 'FLEET', label: 'Fleet programme' }];

export default function AutoAdminPage() {
  const data = useLoad<Overview>(() => autoApi.admin.overview());
  const [decision, setDecision] = useState<Record<string, { status: string; lender: string; note: string; ratePct: string; days: string }>>({});
  const [add, setAdd] = useState({ kind: 'INSURANCE', partner: '', basisAmount: '', fee: '', note: '' });
  const [busy, setBusy] = useState(false);
  const act = async (fn: () => Promise<unknown>, done: string) => { setBusy(true); try { await fn(); toast.success(done); data.reload(); } catch (err) { toast.error(autoError(err, 'That did not work.')); } finally { setBusy(false); } };
  const o = data.data;
  return (
    <div className="mx-auto max-w-5xl space-y-6 p-6">
      <PageTitle icon={ShieldCheck} kicker="Cars · admin" title="Automotive queues" blurb={o ? `${o.counts.verifiedMechanics} verified workshops, ${o.counts.verifiedDealers} dealerships, ${o.counts.liveListings} live listings, ${o.counts.openPurchases} purchases with money held.` : 'Verification, held listings, disputes, finance and inspections.'} />
      <AutoNav current="/dashboard/cars/admin" />
      {data.loading && <Loading />}
      <ErrorBox error={data.error} />
      {o && (
        <div className="space-y-6">
          <Panel title={`Workshops to verify (${o.mechanics.length})`} intro="Check the licence number against the state register and the business against the ABN lookup before verifying.">
            <ul className="space-y-2">{o.mechanics.map((m) => <li key={m.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium text-slate-900 dark:text-white">{m.name} <span className="text-xs font-normal text-slate-500">· {[m.suburb || m.city, m.state].filter(Boolean).join(', ')} · {m.licenceNumber ? `licence ${m.licenceNumber}` : 'no licence number'} · {fmtDay(m.createdAt)}</span></span><div className="flex gap-1"><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.mechanic(m.id, { isVerified: true }), 'Verified')} className="rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-white">Verify</button><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.mechanic(m.id, { isVerified: true, featuredDays: 30 }), 'Verified and featured for 30 days')} className="rounded-md bg-amber-500 px-2 py-1 text-xs font-semibold text-white">Verify and feature</button><Confirm label="Hide" tone="slate" onConfirm={() => act(() => autoApi.admin.mechanic(m.id, { isActive: false }), 'Hidden')} /></div></div><p className="mt-1 text-xs text-slate-600 dark:text-slate-400">{m.headline}. {m.about.slice(0, 200)}</p></li>)}{o.mechanics.length === 0 && <li className="text-sm text-slate-500">None waiting.</li>}</ul>
          </Panel>
          <Panel title={`Dealerships to verify (${o.dealerships.length})`}>
            <ul className="space-y-2">{o.dealerships.map((d) => <li key={d.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><span className="font-medium text-slate-900 dark:text-white">{d.name} <span className="text-xs font-normal text-slate-500">· {d.brands.join(', ') || 'no brands'} · {[d.suburb || d.city, d.state].filter(Boolean).join(', ')} · {d.email ?? ''} · {fmtDay(d.createdAt)}</span></span><div className="flex gap-1"><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.dealership(d.id, { isVerified: true }), 'Verified')} className="rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-white">Verify</button><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.dealership(d.id, { isVerified: true, featuredDays: 30 }), 'Verified and featured')} className="rounded-md bg-amber-500 px-2 py-1 text-xs font-semibold text-white">Verify and feature</button><Confirm label="Hide" tone="slate" onConfirm={() => act(() => autoApi.admin.dealership(d.id, { isActive: false }), 'Hidden')} /></div></li>)}{o.dealerships.length === 0 && <li className="text-sm text-slate-500">None waiting.</li>}</ul>
          </Panel>
          <Panel title={`Listings held by the checks (${o.listings.length})`} intro="Read it as a buyer would. Let it through, or take it down with a reason the seller can act on.">
            <ul className="space-y-2">{o.listings.map((l) => <li key={l.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div className="flex flex-wrap items-center justify-between gap-2"><Link href={`/cars/preloved/${l.id}`} className="font-medium text-slate-900 hover:text-rose-600 dark:text-white">{l.title}</Link><span className="text-xs text-slate-500">{aud0(l.price)} · {km(l.odometerKm)} · {l.seller.name} · score {l.riskScore}</span></div><p className="mt-1 text-xs text-rose-700 dark:text-rose-300">{(l.riskFlags ?? []).join(', ')}</p><div className="mt-2 flex flex-wrap gap-1"><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.listing(l.id, { status: 'ACTIVE' }), 'Live')} className="rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-white">Let it through</button><button type="button" disabled={busy} onClick={() => { const r = window.prompt('Reason the seller will read', 'The price is well under the guide and there are no photos; add photos and the VIN and it can go live.'); if (r) act(() => autoApi.admin.listing(l.id, { status: 'SUSPENDED', suspendedReason: r }), 'Kept held, reason sent'); }} className="rounded-md bg-amber-500 px-2 py-1 text-xs font-semibold text-white">Keep held with a reason</button><Confirm label="Take down" onConfirm={() => act(() => autoApi.admin.listing(l.id, { status: 'WITHDRAWN', suspendedReason: 'Removed by ATHENA' }), 'Taken down')} /></div></li>)}{o.listings.length === 0 && <li className="text-sm text-slate-500">None held.</li>}</ul>
          </Panel>
          <Panel title={`Disputes (${o.disputes.length})`} intro="Both sides have been asked for the facts. Decide on the purchase page.">
            <ul className="space-y-2">{o.disputes.map((p) => <li key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><span><span className="font-medium text-slate-900 dark:text-white">{p.listing.title}</span><span className="text-xs text-slate-500"> · {aud0(p.agreedAmount ?? p.offerAmount)} · {p.buyer.name} v {p.seller.name} · opened {p.disputeOpenedAt ? fmtDay(p.disputeOpenedAt) : ''}</span><p className="mt-1 text-xs text-slate-700 dark:text-slate-300">{p.disputeReason}</p></span><Link href={`/dashboard/cars/purchases/${p.id}`} className="btn-primary text-xs">Decide</Link></li>)}{o.disputes.length === 0 && <li className="text-sm text-slate-500">None open.</li>}</ul>
          </Panel>
          <Panel title={`Finance desk (${o.applications.length})`} intro="Read it the way a lender does. A pre-approval names the lender, the rate and how long it is good for.">
            <ul className="space-y-3">{o.applications.map((a) => { const d = decision[a.id] ?? { status: 'PRE_APPROVED', lender: '', note: '', ratePct: String(a.ratePct), days: '60' }; const setD = (v: Partial<typeof d>) => setDecision((x) => ({ ...x, [a.id]: { ...d, ...v } })); return <li key={a.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium text-slate-900 dark:text-white">{a.referenceCode} · {a.applicant?.name} <span className="text-xs font-normal text-slate-500">{a.applicant?.email}</span></span><StatusChip status={a.status} /></div><p className="mt-1 text-xs text-slate-600 dark:text-slate-400">{aud0(a.amount)} over {a.termMonths} months for a {aud0(a.vehiclePrice)} {a.purpose.toLowerCase()} car · income {aud0(a.incomeAnnual)} · expenses {aud0(a.expensesMonthly)}/mo · other debts {aud0(a.otherDebtsMonthly)}/mo · {a.employment.toLowerCase().replace('_', ' ')}{a.employmentMonths ? ` ${a.employmentMonths} months` : ''} · {a.residency?.toLowerCase() ?? ''} · readiness {a.readinessScore}</p><ul className="mt-1 list-disc pl-5 text-xs text-slate-500">{a.readinessNotes.slice(0, 4).map((n) => <li key={n}>{n}</li>)}</ul><div className="mt-2 grid gap-2 sm:grid-cols-5"><Field label="Decision"><SelectInput value={d.status} onChange={(v) => setD({ status: v })} options={[{ value: 'IN_REVIEW', label: 'In review' }, { value: 'PRE_APPROVED', label: 'Pre-approve' }, { value: 'DECLINED', label: 'Decline' }]} /></Field><Field label="Lender"><input value={d.lender} onChange={(e) => setD({ lender: e.target.value })} className={inputClass} /></Field><Field label="Rate"><NumberInput value={d.ratePct} onChange={(v) => setD({ ratePct: v })} suffix="%" step={0.01} /></Field><Field label="Good for (days)"><NumberInput value={d.days} onChange={(v) => setD({ days: v })} /></Field><div className="flex items-end pb-1"><button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.finance(a.id, { status: d.status, lender: d.lender || undefined, decisionNote: d.note || undefined, ratePct: num(d.ratePct) || undefined, expiresInDays: num(d.days, 60) }), 'Decision sent')} className="btn-primary w-full text-xs">Send</button></div></div><input value={d.note} onChange={(e) => setD({ note: e.target.value })} placeholder="A note the applicant will read" className={`${inputClass} mt-1`} /></li>; })}{o.applications.length === 0 && <li className="text-sm text-slate-500">Nothing waiting.</li>}</ul>
          </Panel>
          <Panel title="Referral fees" intro={`What partners owe for introductions made here: ${aud0(o.referrals.totals.pending)} pending, ${aud0(o.referrals.totals.confirmed)} confirmed and waiting to be invoiced, ${aud0(o.referrals.totals.paid)} received. A pending fee is confirmed once the sale, loan or policy is checked with the partner.`}>
            <ul className="space-y-2">{o.referrals.open.map((r) => <li key={r.id} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium text-slate-900 dark:text-white">{r.kindLabel} · {r.partner ?? 'partner not named'} <span className="text-xs font-normal text-slate-500">· {r.member?.name ?? 'no member'} · {aud0(r.basisAmount)} at {r.feePercent}% · {fmtDay(r.createdAt)}</span></span><span className="flex items-center gap-2"><span className="font-semibold text-slate-900 dark:text-white">{aud0(r.fee)}</span><StatusChip status={r.status} /></span></div>{r.note && <p className="mt-1 text-xs text-slate-600 dark:text-slate-400">{r.note}</p>}<div className="mt-2 flex flex-wrap gap-1">{r.status === 'PENDING' && <button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.referral(r.id, { status: 'CONFIRMED' }), 'Confirmed')} className="rounded-md bg-emerald-500 px-2 py-1 text-xs font-semibold text-white">Confirmed with the partner</button>}<button type="button" disabled={busy} onClick={() => act(() => autoApi.admin.referral(r.id, { status: 'PAID' }), 'Marked paid')} className="rounded-md bg-sky-500 px-2 py-1 text-xs font-semibold text-white">Paid</button><Confirm label="Void" tone="slate" onConfirm={() => act(() => autoApi.admin.referral(r.id, { status: 'VOID' }), 'Voided')} /></div></li>)}{o.referrals.open.length === 0 && <li className="text-sm text-slate-500">Nothing owed right now.</li>}</ul>
            <div className="mt-4 rounded-lg border border-dashed border-slate-300 p-3 dark:border-slate-700">
              <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Add a fee agreed with a partner</p>
              <div className="mt-2 grid gap-2 sm:grid-cols-5"><Field label="Kind"><SelectInput value={add.kind} onChange={(v) => setAdd((x) => ({ ...x, kind: v }))} options={REFERRAL_KINDS} /></Field><Field label="Partner"><input value={add.partner} onChange={(e) => setAdd((x) => ({ ...x, partner: e.target.value }))} className={inputClass} /></Field><Field label="Basis: premium, price, loan"><NumberInput value={add.basisAmount} onChange={(v) => setAdd((x) => ({ ...x, basisAmount: v }))} prefix="$" /></Field><Field label="Fee, if not the standard"><NumberInput value={add.fee} onChange={(v) => setAdd((x) => ({ ...x, fee: v }))} prefix="$" /></Field><div className="flex items-end pb-1"><button type="button" disabled={busy || !add.partner.trim() || num(add.basisAmount) <= 0} onClick={() => act(() => autoApi.admin.addReferral({ kind: add.kind, partner: add.partner, basisAmount: num(add.basisAmount), fee: add.fee ? num(add.fee) : undefined, note: add.note || undefined }), 'Added to the ledger')} className="btn-primary w-full text-xs disabled:opacity-50">Add</button></div></div>
              <input value={add.note} onChange={(e) => setAdd((x) => ({ ...x, note: e.target.value }))} placeholder="A note: the policy, invoice or order reference" className={`${inputClass} mt-1`} />
            </div>
            <p className="mt-2 text-xs leading-5 text-slate-500">{Object.values(o.referrals.fees).map((f) => f.words).join(' ')}</p>
          </Panel>
          <Panel title={`Inspection requests nobody has taken (${o.inspections.length})`} intro="Workshops that do inspections in the state have been told. If one sits, ring a workshop.">
            <ul className="space-y-1">{o.inspections.map((i) => <li key={i.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-50 p-2 text-sm dark:bg-slate-800/60"><span>{i.listing.year} {i.listing.make} {i.listing.model} · {i.listing.state} · {fmtDay(i.createdAt)} · asked by {i.requestedBy}</span><Link href={`/cars/preloved/${i.listing.id}`} className="btn-ghost text-xs">Listing</Link></li>)}{o.inspections.length === 0 && <li className="text-sm text-slate-500">None waiting.</li>}</ul>
          </Panel>
        </div>
      )}
    </div>
  );
}
