'use client';

import React, { useState } from 'react';
import { 
  BrainCircuit, Sparkles, TrendingUp, ArrowRight, CheckCircle,
  Briefcase, Search, Filter, Target,
  ChevronRight, Download, X, Plus, Calendar, Zap,
  LayoutDashboard, Share2, Bookmark, GraduationCap, LineChart
} from 'lucide-react';

// --- Types ---
type ViewState = 'overview' | 'skills' | 'market' | 'jobs' | 'learning';

interface Insight {
  id: string;
  title: string;
  type: 'Prediction' | 'Analysis' | 'Recommendation';
  confidence: number;
  date: string;
  description: string;
}

interface SkillGap {
  id: string;
  skill: string;
  currentLevel: 'Beginner' | 'Intermediate' | 'Advanced';
  targetLevel: 'Intermediate' | 'Advanced' | 'Expert';
  priority: 'High' | 'Medium' | 'Low';
}

// --- Mock Data ---
const INSIGHTS: Insight[] = [
  { id: '1', title: 'Role Transition Probability', type: 'Prediction', confidence: 85, date: 'Dec 12, 2025', description: 'Based on your recent project history, you are 85% ready for a Senior Architect role.' },
  { id: '2', title: 'Emerging Skill Demand', type: 'Analysis', confidence: 92, date: 'Dec 10, 2025', description: 'Demand for "Rust" in your industry has increased by 40% in the last quarter.' },
  { id: '3', title: 'Leadership Potential', type: 'Analysis', confidence: 78, date: 'Dec 05, 2025', description: 'Your communication patterns suggest strong potential for team leadership.' },
  { id: '4', title: 'Recommended Certification', type: 'Recommendation', confidence: 95, date: 'Nov 28, 2025', description: 'Completing "AWS Solutions Architect" would increase your market value by approx. 15%.' },
];

const SKILL_GAPS: SkillGap[] = [
  { id: '1', skill: 'System Design', currentLevel: 'Intermediate', targetLevel: 'Advanced', priority: 'High' },
  { id: '2', skill: 'Cloud Infrastructure', currentLevel: 'Intermediate', targetLevel: 'Expert', priority: 'High' },
  { id: '3', skill: 'Team Management', currentLevel: 'Beginner', targetLevel: 'Intermediate', priority: 'Medium' },
];

// --- Components ---
const InsightViewer = ({ insight, onClose }: { insight: Insight; onClose: () => void }) => (
  <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-in fade-in duration-200">
    <div className="bg-white rounded-2xl w-full max-w-2xl flex flex-col shadow-2xl overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-slate-100">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-fuchsia-100 rounded-lg flex items-center justify-center">
            <BrainCircuit className="w-5 h-5 text-fuchsia-600" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900">{insight.type}</h3>
            <p className="text-xs text-slate-500">{insight.date} • {insight.confidence}% Confidence</p>
          </div>
        </div>
        <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-lg transition-colors text-slate-600">
          <X className="w-5 h-5" />
        </button>
      </div>
      <div className="p-8 bg-slate-50 flex flex-col items-center text-center">
        <div className="w-20 h-20 bg-white rounded-full flex items-center justify-center shadow-sm mb-6">
          <Sparkles className="w-10 h-10 text-fuchsia-500" />
        </div>
        <h2 className="text-2xl font-bold text-slate-900 mb-4">{insight.title}</h2>
        <p className="text-slate-600 mb-8 max-w-md leading-relaxed">
          {insight.description}
        </p>
        <div className="w-full bg-white p-6 rounded-xl border border-slate-200 text-left">
          <h4 className="font-bold text-slate-900 mb-2 text-sm">AI Analysis</h4>
          <p className="text-xs text-slate-500">
            This insight was generated by analyzing 150+ data points from your work history, market trends, and peer comparisons.
          </p>
        </div>
      </div>
    </div>
  </div>
);

interface OverviewViewProps {
  onSelectInsight: (insight: Insight) => void;
  onNavigate: (view: ViewState) => void;
}

const OverviewView = ({ onSelectInsight, onNavigate }: OverviewViewProps) => (
  <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
    {/* Hero Card */}
    <div className="relative bg-slate-900/50 rounded-3xl overflow-hidden p-8 md:p-12">
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10" />
      <div className="absolute top-0 right-0 w-2/3 h-full bg-linear-to-l from-fuchsia-900/40 to-transparent" />
      
      <div className="relative z-10 max-w-2xl">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-fuchsia-500/20 border border-fuchsia-500/30 backdrop-blur-sm mb-6">
          <BrainCircuit className="w-4 h-4 text-fuchsia-400" />
          <span className="text-xs font-bold text-fuchsia-100 uppercase tracking-wider">AI Career Coach</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-6 leading-tight">
          Future-proof your <span className="text-fuchsia-500">Career.</span>
        </h1>
        <p className="text-lg text-slate-300 mb-8">
          Leverage AI to analyze your skills, predict market trends, and identify your next big opportunity.
        </p>
        <div className="flex flex-wrap gap-4">
          <button onClick={() => onNavigate('skills')} className="px-6 py-3 bg-fuchsia-600 hover:bg-fuchsia-700 text-white rounded-xl font-bold transition-colors flex items-center gap-2">
            Analyze Skills <ArrowRight className="w-4 h-4" />
          </button>
          <button onClick={() => onNavigate('market')} className="px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-bold transition-colors backdrop-blur-sm">
            Market Trends
          </button>
        </div>
      </div>
    </div>

    {/* Quick Stats */}
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 bg-fuchsia-50 rounded-lg flex items-center justify-center">
            <Target className="w-5 h-5 text-fuchsia-600" />
          </div>
          <span className="text-xs font-bold text-fuchsia-600 bg-fuchsia-50 px-2 py-1 rounded-full">High</span>
        </div>
        <div className="text-3xl font-bold text-slate-900 mb-1">92%</div>
        <div className="text-sm text-slate-500">Role Match Score</div>
      </div>
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 bg-blue-50 rounded-lg flex items-center justify-center">
            <TrendingUp className="w-5 h-5 text-blue-600" />
          </div>
          <span className="text-xs font-bold text-slate-500">Growth</span>
        </div>
        <div className="text-3xl font-bold text-slate-900 mb-1">+15%</div>
        <div className="text-sm text-slate-500">Salary Potential</div>
      </div>
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <div className="w-10 h-10 bg-emerald-50 rounded-lg flex items-center justify-center">
            <Zap className="w-5 h-5 text-emerald-600" />
          </div>
          <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">Active</span>
        </div>
        <div className="text-3xl font-bold text-slate-900 mb-1">3</div>
        <div className="text-sm text-slate-500">Skill Gaps Identified</div>
      </div>
    </div>

    {/* Content Grid */}
    <div className="grid lg:grid-cols-3 gap-8">
      {/* AI Insights */}
      <div className="lg:col-span-2 space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-slate-900">AI Insights</h2>
          <button className="text-sm font-bold text-fuchsia-600 hover:text-fuchsia-700">Refresh Analysis</button>
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          {INSIGHTS.map((insight) => (
            <div 
              key={insight.id}
              onClick={() => onSelectInsight(insight)}
              className="group bg-white p-4 rounded-xl border border-slate-200 hover:border-fuchsia-200 hover:shadow-md transition-all cursor-pointer flex flex-col h-full"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="w-10 h-10 bg-slate-50 rounded-lg flex items-center justify-center group-hover:bg-fuchsia-50 transition-colors">
                  <Sparkles className="w-5 h-5 text-slate-400 group-hover:text-fuchsia-500 transition-colors" />
                </div>
                <span className="text-xs font-bold text-slate-400 bg-slate-50 px-2 py-1 rounded-full">{insight.type}</span>
              </div>
              
              <h3 className="font-bold text-slate-900 group-hover:text-fuchsia-700 transition-colors mb-2">{insight.title}</h3>
              <p className="text-sm text-slate-500 line-clamp-2 mb-4 flex-1">{insight.description}</p>
              
              <div className="flex items-center justify-between text-xs text-slate-400 pt-3 border-t border-slate-50">
                <span className="flex items-center gap-1"><Calendar className="w-3 h-3" /> {insight.date}</span>
                <span className="flex items-center gap-1 text-fuchsia-600 font-bold">{insight.confidence}% Conf.</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Skill Gaps */}
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-bold text-slate-900">Focus Areas</h2>
        </div>
        <div className="bg-white p-6 rounded-2xl border border-slate-200">
          <div className="space-y-4">
            {SKILL_GAPS.map((gap) => (
              <div key={gap.id} className="flex items-center justify-between">
                <div>
                  <h4 className="font-bold text-slate-900 text-sm">{gap.skill}</h4>
                  <div className="flex items-center gap-2 text-xs mt-1">
                    <span className="text-slate-500">{gap.currentLevel}</span>
                    <ArrowRight className="w-3 h-3 text-slate-300" />
                    <span className="text-fuchsia-600 font-bold">{gap.targetLevel}</span>
                  </div>
                </div>
                <span className={`text-xs font-bold px-2 py-1 rounded-full ${
                  gap.priority === 'High' ? 'bg-rose-50 text-rose-600' : 'bg-amber-50 text-amber-600'
                }`}>
                  {gap.priority}
                </span>
              </div>
            ))}
          </div>
          <button className="w-full mt-6 py-2 bg-fuchsia-50 text-fuchsia-700 rounded-lg text-sm font-bold hover:bg-fuchsia-100 transition-colors">
            View Learning Plan
          </button>
        </div>
        
        <div className="p-6 bg-slate-900 rounded-2xl text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-fuchsia-600 rounded-full -mr-16 -mt-16 opacity-20" />
          <div className="relative z-10">
            <h3 className="font-bold text-lg mb-2">Career Simulation</h3>
            <p className="text-slate-300 text-sm mb-4">Simulate how different career choices impact your long-term growth.</p>
            <button className="w-full py-2 bg-fuchsia-600 text-white rounded-lg text-sm font-bold hover:bg-fuchsia-700 transition-colors">
              Start Simulation
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default function CareerInsightsPage() {
  const [currentView, setCurrentView] = useState<ViewState>('overview');
  const [selectedInsight, setSelectedInsight] = useState<Insight | null>(null);

  return (
    <div className="min-h-screen bg-slate-50 font-sans flex">
      {/* Sidebar Navigation */}
      <div className="w-64 bg-white border-r border-slate-200 hidden lg:flex flex-col p-4 sticky top-0 h-screen">
        <div className="mb-8 px-4 pt-4">
          <div className="flex items-center gap-2 text-fuchsia-600 font-bold text-xl">
            <BrainCircuit className="w-6 h-6" />
            <span>Career AI</span>
          </div>
        </div>
        
        <nav className="space-y-1 flex-1">
          <button onClick={() => setCurrentView('overview')} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all w-full text-left ${currentView === 'overview' ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' : 'text-slate-600 hover:bg-slate-100'}`}><LayoutDashboard className="w-5 h-5" /><span className="font-medium">Overview</span></button>
          <button onClick={() => setCurrentView('skills')} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all w-full text-left ${currentView === 'skills' ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' : 'text-slate-600 hover:bg-slate-100'}`}><Target className="w-5 h-5" /><span className="font-medium">Skill Analysis</span></button>
          <button onClick={() => setCurrentView('market')} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all w-full text-left ${currentView === 'market' ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' : 'text-slate-600 hover:bg-slate-100'}`}><LineChart className="w-5 h-5" /><span className="font-medium">Market Trends</span></button>
          <button onClick={() => setCurrentView('jobs')} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all w-full text-left ${currentView === 'jobs' ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' : 'text-slate-600 hover:bg-slate-100'}`}><Briefcase className="w-5 h-5" /><span className="font-medium">Job Matches</span></button>
          <button onClick={() => setCurrentView('learning')} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all w-full text-left ${currentView === 'learning' ? 'bg-fuchsia-600 text-white shadow-lg shadow-fuchsia-600/20' : 'text-slate-600 hover:bg-slate-100'}`}><GraduationCap className="w-5 h-5" /><span className="font-medium">Learning Path</span></button>
        </nav>

        <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 mt-4">
          <h4 className="font-bold text-slate-900 mb-2 text-sm">Upgrade to Pro</h4>
          <p className="text-xs text-slate-500 mb-3">Get unlimited AI career simulations.</p>
          <button className="w-full py-2 bg-white border border-slate-200 rounded-lg text-xs font-bold text-slate-700 hover:bg-slate-50">
            View Plans
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 p-4 md:p-8 pb-24 lg:pb-8 overflow-y-auto h-screen">
        {currentView === 'overview' && <OverviewView onSelectInsight={setSelectedInsight} onNavigate={setCurrentView} />}
        {/* Placeholders for other views */}
        {currentView !== 'overview' && (
          <div className="flex items-center justify-center h-full text-slate-500">
            View content coming soon...
          </div>
        )}
      </div>

      {/* Modals */}
      {selectedInsight && (
        <InsightViewer insight={selectedInsight} onClose={() => setSelectedInsight(null)} />
      )}
    </div>
  );
}